import Link from 'next/link';
import SiteHeader from '../../components/SiteHeader';
import SiteFooter from '../../components/SiteFooter';

const distances = [['Marbella','Aprox. 15 minutos'],['Puerto Banús','Aprox. 15 minutos'],['Playas','Aprox. 15 minutos'],['Campos de golf','Aprox. 10–20 minutos'],['Aeropuerto de Málaga','Aprox. 45 minutos']];
const qualities = [['Privacidad','Grandes parcelas, arbolado maduro y una discreta ubicación en la ladera crean una extraordinaria sensación de intimidad.'],['Seguridad','Accesos controlados y seguridad profesional 24 horas ofrecen absoluta tranquilidad.'],['Naturaleza','Aire de montaña, árboles consolidados y carreteras privadas aportan calma frente a la costa.'],['Accesibilidad','Marbella, Puerto Banús, playas, restaurantes y golf quedan a poca distancia.']];

export const metadata = {
  title: 'El Madroñal, Marbella',
  description: 'Guía de El Madroñal en Benahavís: privacidad, seguridad, villas, naturaleza y acceso a Marbella, Puerto Banús, golf y playas.',
  alternates: { canonical: '/es/el-madronal', languages: { en: '/el-madronal', es: '/es/el-madronal', 'x-default': '/el-madronal' } }
};

export default function ElMadronal() { return <>
  <SiteHeader locale="es" languageHref="/el-madronal" />
  <main>
    <section className="villaHero estateHero"><div className="shade" /><div className="wrap heroCopy"><p className="eyebrow">El Madroñal · Benahavís</p><h1>Sobre Marbella.<em>Un mundo aparte.</em></h1><p>Una urbanización privada de carreteras de montaña, bosque maduro y residencias excepcionales, a pocos minutos del Mediterráneo.</p></div></section>
    <section className="intro pad"><div className="wrap split"><p className="eyebrow darkEye">La urbanización</p><div><h2>Calma sin aislamiento.<em>Privacidad sin renuncias.</em></h2><p className="lead">El Madroñal ocupa una posición privilegiada en las colinas de Benahavís, sobre Marbella. Su entorno natural, amplias parcelas y accesos controlados lo han convertido en una de las direcciones residenciales más discretas de la Costa del Sol.</p></div></div></section>
    <section className="pad estateQualities"><div className="wrap qualityGrid">{qualities.map(([title,copy],index)=><article key={title}><span>0{index+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section className="featureSplit darkFeature"><div className="featureImage estateNatureFeature" /><div className="featureCopy"><p className="eyebrow">Un refugio natural</p><h2>Calma de montaña.<em>Luz mediterránea.</em></h2><p>Carreteras privadas serpentean entre alcornoques, pinos y jardines maduros. La altura aporta aire más fresco en verano, vistas abiertas y auténtica tranquilidad.</p><p>A diferencia de las zonas costeras más densas, El Madroñal mantiene una estrecha relación con el paisaje andaluz.</p></div></section>
    <section className="pad estateLocation"><div className="wrap locationPanel"><div><p className="eyebrow darkEye">Ubicación privilegiada</p><h2>Cerca de todo.<em>Lejos del ruido.</em></h2><p className="lead locationLead">La calma de la villa convive con un acceso cómodo a playas, restaurantes, puertos deportivos, golf y conexiones internacionales.</p></div><dl>{distances.map(([place,time])=><div key={place}><dt>{place}</dt><dd>{time}</dd></div>)}</dl></div></section>
    <section className="pad editorial"><div className="wrap editorialGrid"><div><p className="eyebrow darkEye">Conocer El Madroñal</p><h2>Una urbanización consolidada.<em>Con carácter propio.</em></h2></div><div className="copyColumns"><p>El Madroñal es una comunidad residencial privada y consolidada dentro del municipio de Benahavís, justo por encima de la costa de Marbella. No es un resort convencional, sino un conjunto de villas de diseño individual entre carreteras tranquilas y vegetación madura.</p><p>La urbanización se organiza alrededor de varios accesos controlados. La entrada, orientación y altitud influyen en la experiencia de cada propiedad, por lo que distintas zonas de El Madroñal pueden ofrecer ambientes y vistas muy diferentes.</p></div></div></section>
    <section className="pad lifestyleSection"><div className="wrap heading"><div><p className="eyebrow darkEye">Vivir El Madroñal</p><h2>Espacio, naturaleza.<em>Y Marbella al alcance.</em></h2></div><p>Su atractivo está en la combinación: un entorno de montaña realmente privado sin renunciar a restaurantes, playas, golf, compras y conexiones internacionales.</p></div><div className="wrap lifestyleCards"><article><span>01</span><h3>Marbella y Puerto Banús</h3><p>La costa queda cerca para comer, comprar, disfrutar del puerto o salir por la noche, regresando después a la tranquilidad de la montaña.</p></article><article><span>02</span><h3>Benahavís y gastronomía</h3><p>Benahavís y Marbella ofrecen desde cocina andaluza tradicional hasta alta gastronomía internacional y servicios de chef privado.</p></article><article><span>03</span><h3>Golf y naturaleza</h3><p>El Madroñal se encuentra entre algunos de los campos de golf más conocidos de la Costa del Sol, con las colinas cercanas ideales también para caminar y disfrutar del aire libre.</p></article></div></section>
    <section className="featureSplit reverseFeature"><div className="featureImage estateSecurityFeature" /><div className="featureCopy lightCopy"><p className="eyebrow darkEye">Seguridad y discreción</p><h2>Confianza desde la llegada.<em>Privacidad durante su estancia.</em></h2><p>Entradas controladas, seguridad profesional y tranquilas vías privadas permiten relajarse desde el primer momento.</p><div className="serviceList compactList"><span>Seguridad 24 horas</span><span>Acceso de vehículos controlado</span><span>Gestión profesional</span><span>Carreteras privadas tranquilas</span><span>Baja densidad residencial</span><span>Máxima discreción</span></div></div></section>
    <section className="pad estateLocation"><div className="wrap locationPanel"><div><p className="eyebrow darkEye">Para huéspedes y residentes</p><h2>Vida privada.<em>Práctica cada día.</em></h2><p className="lead locationLead">Aunque el entorno se siente apartado, supermercados, restaurantes, colegios, sanidad privada, beach clubs y centros deportivos están disponibles en el área de Benahavís y Marbella.</p></div><div className="serviceList compactList"><span>Gastronomía internacional</span><span>Supermercados</span><span>Sanidad privada</span><span>Colegios internacionales</span><span>Golf y deportes de raqueta</span><span>Playas y beach clubs</span></div></div></section>
    <section className="pad collectionCta"><div className="wrap collectionInner"><p className="eyebrow darkEye">Alquiler de villas de lujo</p><h2>Disfrute Marbella.<em>Encuentre la villa adecuada.</em></h2><p>Villa Candela y Villa Lámpara se mantienen actualmente para uso privado. A través de Property Facilitators EuroAsia y The Luxury Villa Collection puede explorar más de 100 villas de lujo en alquiler en Marbella, Benahavís, El Madroñal y otras zonas prime.</p><div className="actions"><a className="btn gold" href="https://www.pfeuroasia.com/luxury-villa-rentals">Explorar más de 100 villas</a></div></div></section>
    <section className="pad collectionCta"><div className="wrap collectionInner"><p className="eyebrow darkEye">La colección privada</p><h2>Dos villas excepcionales.<em>Una urbanización extraordinaria.</em></h2><p>Descubra Villa Candela y Villa Lámpara, dos interpretaciones de la privacidad, el lujo y la vida mediterránea.</p><div className="actions"><Link className="btn gold" href="/es/villa-candela">Descubrir Villa Candela</Link><Link className="under" href="/es/villa-lampara">Descubrir Villa Lámpara</Link></div></div></section>
  </main><SiteFooter locale="es" />
</>; }
