import Link from 'next/link';
import SiteHeader from '../../components/SiteHeader';
import SiteFooter from '../../components/SiteFooter';

const insights = [
  ['01','El acceso forma parte de la dirección','El Madroñal se extiende por una ladera con varios accesos y recorridos muy distintos. La entrada más práctica depende de la ubicación, la hora y el destino.'],
  ['02','La orientación cambia la experiencia','Dos villas cercanas pueden sentirse muy diferentes. Altura, orientación, arbolado y forma de la parcela influyen en la luz, las vistas, la privacidad y el uso de los exteriores.'],
  ['03','La privacidad es más que el tamaño','Una gran parcela importa, pero el paisajismo, las vistas desde viviendas vecinas, la posición respecto a la vía y la ubicación de terrazas y piscina suelen marcar la diferencia.'],
  ['04','Una gran villa necesita cuidado continuo','Jardines, piscinas, agua, seguridad, accesos, personal y mantenimiento preventivo requieren coordinación. Una buena gestión protege el disfrute y el valor de la vivienda.']
];
const guideLinks = [['La urbanización','/es/descubrir/la-urbanizacion'],['Ubicación y accesos','/es/descubrir/ubicacion'],['Servicios cercanos','/es/descubrir/servicios-cercanos'],['Gastronomía','/es/descubrir/gastronomia'],['Golf y aire libre','/es/descubrir/aire-libre'],['Playas','/es/descubrir/playas']];

export const metadata = {
  title: 'Conocimiento local de El Madroñal | Geoff Harding',
  description: 'Conocimiento práctico de El Madroñal de Geoff Harding, residente en la Costa del Sol desde 1984 y vinculado a villas de la urbanización desde 2010.',
  alternates: { canonical: '/es/conocimiento-local', languages: { en: '/local-knowledge', es: '/es/conocimiento-local', 'x-default': '/local-knowledge' } },
  openGraph: { title: 'Conocimiento local de El Madroñal | Madroñal Villas', description: 'Una perspectiva práctica sobre vivir, poseer, alquilar y comprar en El Madroñal.', url: '/es/conocimiento-local', type: 'article' }
};

export default function ConocimientoLocal() {
  const schema = {'@context':'https://schema.org','@type':'ProfilePage',inLanguage:'es',name:'Conocimiento local de El Madroñal',url:'https://www.madronalvillas.com/es/conocimiento-local',mainEntity:{'@type':'Person','@id':'https://www.madronalvillas.com/local-knowledge#geoff-harding',name:'Geoff Harding',jobTitle:'Asesor inmobiliario y gestor de villas',description:'Residente en la Costa del Sol desde 1984 y vinculado directamente a villas privadas de El Madroñal desde 2010.',knowsAbout:['El Madroñal','Propiedad en Marbella','Gestión de villas','Alquiler de villas de lujo']}};
  return <><SiteHeader locale="es" languageHref="/local-knowledge" /><main>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,'\\u003c')}} />
    <section className="discoverHero knowledgeHero"><div className="shade" /><div className="wrap heroCopy"><p className="eyebrow">Conocimiento local · El Madroñal</p><h1>Experiencia que va<em>más allá del anuncio.</em></h1><p>Una perspectiva práctica nacida de gestionar viviendas, recibir huéspedes y asesorar a propietarios en El Madroñal desde 2010.</p></div></section>
    <section className="intro pad"><div className="wrap split"><p className="eyebrow darkEye">Comprender la urbanización</p><div><h2>Cada camino, orientación y parcela<em>posee su propio carácter.</em></h2><p className="lead">El Madroñal no es una urbanización uniforme. Es una comunidad madura de montaña donde la altura, la orientación, los accesos y el paisajismo pueden importar tanto como la propia villa. Un buen asesoramiento empieza por comprender esas diferencias.</p></div></div></section>
    <section className="pad knowledgeInsights"><div className="wrap"><div className="heading knowledgeHeading"><div><p className="eyebrow darkEye">El valor del conocimiento local</p><h2>Detalles que definen<em>el día a día.</em></h2></div><p>Orientación útil para huéspedes, compradores y propietarios que contemplan una vivienda en esta comunidad singular.</p></div><div className="insightGrid">{insights.map(([number,title,copy])=><article key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <section className="featureSplit knowledgePerspective"><div className="featureImage knowledgeFeatureImage" /><div className="featureCopy"><p className="eyebrow">Una perspectiva práctica</p><h2>Vivir bien en<em>El Madroñal.</em></h2><p>La urbanización ofrece calma y discreción sin alejarse de la costa. También importa lo práctico: elegir el acceso correcto, coordinar servicios domésticos, cuidar grandes jardines y preparar la vivienda para periodos de ocupación o ausencia.</p><p>Ese conocimiento operativo ayuda a distinguir entre una visita atractiva y una vivienda que funcionará excepcionalmente bien con el paso del tiempo.</p><div className="actions"><Link className="btn gold" href="/es/el-madronal">Descubrir la urbanización</Link></div></div></section>
    <section className="pad geoffProfile" id="geoff-harding"><div className="wrap geoffProfileGrid"><div className="profileMarker" aria-hidden="true"><span>GH</span><small>El Madroñal · Desde 2010</small></div><div className="profileCopy"><p className="eyebrow darkEye">Sobre Geoff Harding</p><h2>Una larga vinculación local.<em>Asesoramiento personal e informado.</em></h2><p className="lead">Geoff Harding vive en la Costa del Sol desde 1984 y está directamente vinculado a villas privadas de El Madroñal desde 2010. Su experiencia abarca gestión de villas, alquiler de lujo, representación de propietarios y vivienda residencial de alto valor.</p><p>A través de Madroñal Villas, Geoff ha ayudado a propietarios a cuidar sus viviendas y ha recibido a huéspedes internacionales. Hoy también asesora a clientes mediante Property Facilitators Iberia, colabora con Aylesford Spain en propiedades prime seleccionadas de Marbella y trabaja con PF EuroAsia para clientes internacionales. Su enfoque es sencillo: comprender a la persona, comprender la propiedad y ofrecer consejos claros basados en experiencia directa.</p><div className="actions profileActions"><a className="btn gold" href="https://pfiberia.com/">Asesoramiento inmobiliario en Marbella</a><a className="under" href="https://www.pfeuroasia.com/">Clientes internacionales</a></div></div></div></section>
    <section className="pad localGuideLinks"><div className="wrap"><div className="heading"><div><p className="eyebrow">La guía local</p><h2>Descubra El Madroñal<em>y su entorno.</em></h2></div><p>Empiece por aquello que más le interesa: accesos, vida cotidiana, playas, gastronomía y actividades al aire libre.</p></div><div className="guideLinkGrid">{guideLinks.map(([label,href])=><Link href={href} key={href}><span>{label}</span><b aria-hidden="true">→</b></Link>)}</div></div></section>
  </main><SiteFooter locale="es" /></>;
}
