import SiteHeader from '../../components/SiteHeader';
import SiteFooter from '../../components/SiteFooter';

const galleryImages = ['aerial','pool','sun-terrace','breakfast-terrace','upper-terrace','lounge-main','lounge-wide','entrance','dining','courtyard','bbq-terrace','master-suite','master-suite-wide','family-suite','family-bathroom','bedroom-3','bedroom-4','bedroom-5','bedroom-6'];
const highlights = [['7','Suites'],['14','Comensales en interior'],['20','Comensales en exterior'],['40–50','Capacidad para eventos'],['1.100 m²','Superficie construida aprox.'],['Wi-Fi 7','Conectividad en toda la propiedad']];
const outdoorFeatures = ['Piscina infinita climatizada de agua salada','Zona de poca profundidad para niños','Dos zonas de barbacoa','Plataforma exterior para celebraciones','Bar privado y frigoríficos profesionales','Jardines y solárium'];

export const metadata = {
  title: 'Villa Lámpara',
  description: 'Villa privada de siete dormitorios con piscina infinita climatizada de agua salada en El Madroñal, Marbella.',
  alternates: { canonical: '/es/villa-lampara', languages: { en: '/villa-lampara', es: '/es/villa-lampara', 'x-default': '/villa-lampara' } }
};

export default function VillaLampara() { return <>
  <SiteHeader locale="es" languageHref="/villa-lampara" />
  <main>
    <section className="villaHero lamparaHero"><div className="shade" /><div className="wrap heroCopy"><p className="eyebrow">Villa Lámpara · El Madroñal</p><h1>Lujo contemporáneo.<em>Creado para vivir al aire libre.</em></h1><p>Una residencia privada de siete dormitorios con piscina infinita climatizada de agua salada, magníficas zonas de reunión y absoluta tranquilidad entre montañas.</p><div className="actions"><a className="btn gold" href="https://www.pfeuroasia.com/luxury-villa-rentals#villa-enquiry">Encontrar una villa disponible</a><a className="under" href="#gallery">Descubrir la villa</a></div></div></section>
    <section className="intro pad"><div className="wrap split"><p className="eyebrow darkEye">Villa Lámpara</p><div><h2>Elegancia relajada.<em>Sobre Marbella.</em></h2><p className="lead">Villa Lámpara combina interiores generosos, terrazas ajardinadas y una espectacular piscina para crear un hogar privado pensado para la familia, las celebraciones y la vida mediterránea.</p></div></div></section>
    <section className="statsBand"><div className="wrap statsGrid">{highlights.map(([n,l])=><div className="stat" key={l}><strong>{n}</strong><span>{l}</span></div>)}</div></section>
    <section className="pad editorial"><div className="wrap editorialGrid"><div><p className="eyebrow darkEye">La residencia</p><h2>Un hogar privado en la ladera.<em>Cálido, abierto y acogedor.</em></h2></div><div className="copyColumns"><p>Aproximadamente 1.100 m² distribuidos en luminosos salones, suites y terrazas que se abren naturalmente hacia los jardines.</p><p>La arquitectura es contemporánea sin resultar formal. Grandes ventanales enmarcan las montañas y conectan los principales espacios con la piscina y los exteriores.</p></div></div></section>
    <section className="featureSplit darkFeature"><div className="featureImage lamparaPoolFeature" /><div className="featureCopy"><p className="eyebrow">La piscina infinita</p><h2>El corazón de la villa.<em>De la mañana a la noche.</em></h2><p>La piscina infinita climatizada de agua salada es el centro natural de Villa Lámpara. Los más pequeños disponen de una zona propia y las amplias terrazas permiten tomar el sol, comer y disfrutar de las vistas a la montaña.</p><ul className="cleanList">{outdoorFeatures.map(item=><li key={item}>{item}</li>)}</ul></div></section>
    <section className="pad lifestyleSection"><div className="wrap heading"><div><p className="eyebrow darkEye">Vida interior y exterior</p><h2>Espacio para reunirse.<em>Privacidad cuando importa.</em></h2></div><p>Comedor interior para catorce, exterior para veinte y una plataforma para unas cuarenta o cincuenta personas hacen de Villa Lámpara un espacio muy versátil.</p></div><div className="wrap lifestyleCards">
      <article><span>01</span><h3>Celebraciones</h3><p>Dos barbacoas, bar privado, refrigeración profesional y grandes terrazas facilitan cualquier encuentro.</p></article>
      <article><span>02</span><h3>Vida familiar</h3><p>Siete suites, salones flexibles y piscina infantil para grupos multigeneracionales.</p></article>
      <article><span>03</span><h3>Tecnología</h3><p>Fibra de 1 Gbps, Wi-Fi 7, IPTV y televisor de 75 pulgadas para conectividad y entretenimiento.</p></article>
    </div></section>
    <section id="gallery" className="pad gallerySection"><div className="wrap galleryHeading"><p className="eyebrow darkEye">Galería</p><h2>Villa Lámpara.<em>Por dentro y por fuera.</em></h2></div><div className="wrap gallery">{galleryImages.map((image,index)=><figure className={index%7===0?'wide':''} key={image}><img src={`/images/lampara/${image}.webp`} alt={`Villa Lámpara — ${image.replaceAll('-',' ')}`} /></figure>)}</div></section>
    <section className="featureSplit reverseFeature"><div className="featureImage lamparaTerraceFeature" /><div className="featureCopy lightCopy"><p className="eyebrow darkEye">El estándar Madroñal</p><h2>Seguridad y servicio.<em>Absoluta discreción.</em></h2><p>Seguridad privada 24 horas, personal residente, limpieza profesional, ropa de cama de calidad hotelera y conserjería adaptada a cada estancia.</p><div className="serviceList compactList"><span>Chefs privados</span><span>Traslados al aeropuerto</span><span>Vehículos de lujo</span><span>Alquiler de yates</span><span>Reservas de golf</span><span>Tratamientos de bienestar</span></div></div></section>
    <section id="enquire" className="contact pad"><div className="wrap contactGrid"><div><p className="eyebrow">Disponibilidad actual</p><h2>Villa Lámpara no está<em>actualmente en alquiler.</em></h2><p>Property Facilitators EuroAsia y The Luxury Villa Collection pueden preparar una selección personalizada de villas de lujo disponibles.</p></div><div><p>Indique fechas, número de huéspedes, dormitorios, zona preferida y presupuesto aproximado para recibir alternativas adecuadas.</p><div className="actions"><a className="btn gold" href="https://www.pfeuroasia.com/luxury-villa-rentals#villa-enquiry">Solicitar villas disponibles</a></div></div></div></section>
  </main><SiteFooter locale="es" />
</>; }
